(define (problem pb1)
(:domain tsp)
(:objects
	boston newyork pittsburgh toronto albany - position
	zero one two three four five - order)
(:init
	(connected newyork boston)
	(connected pittsburgh newyork)
	(connected newyork albany)
	(at pittsburgh)
	(connected boston pittsburgh)
	(connected boston newyork)
	(connected pittsburgh boston)
	(connected toronto pittsburgh)
	(connected toronto newyork)
	(connected albany newyork)
	(connected albany toronto)
	(connected toronto albany)
	(connected newyork pittsburgh)
	(connected newyork toronto)
	
	;; numbers
	(before zero one)
	(before zero two)
	(before zero three)
	(before zero four)
	(before zero five)
	(before one two)
	(before one three)
	(before one four)
	(before one five)
	(before two three)
	(before two four)
	(before two five)
	(before three four)
	(before three five)
	(before four five)
	(last zero)
	
	;; found plan
	(plan-action-MOVE one PITTSBURGH BOSTON)
	(plan-action-MOVE two BOSTON NEWYORK)
	(plan-action-MOVE three NEWYORK ALBANY)
	(plan-action-MOVE four ALBANY TORONTO)
	(plan-action-MOVE five TORONTO PITTSBURGH)
)
(:goal
	(and
		(visited albany)
		(visited boston)
		(at pittsburgh)
		(visited toronto)
		(visited newyork)
		(visited pittsburgh)
	)
)
)