(define (problem pb1)
(:domain dwr)
(:objects
	r1 - robot
	l1 l2 - location
	k1 k2 - crane
	p1 q1 p2 q2 - pile
	ca cb cc cd ce cf pallet - container
	zero one two three four five six seven eight nine ten eleven twelve thirteen fourteen fifteen sixteen seventeen - order)
(:init
	(equal pallet pallet)
	(at r1 l1)
	(attached p2 l2)
	(top pallet p2)
	(occupied l1)
	(attached p1 l1)
	(attached q1 l1)
	(in cc p1)
	(equal cb cb)
	(equal cf cf)
	(equal ce ce)
	(on cb ca)
	(top pallet q2)
	(equal cd cd)
	(belong k2 l2)
	(on cf ce)
	(attached q2 l2)
	(on ca pallet)
	(in cf q1)
	(empty k1)
	(adjacent l1 l2)
	(top cc p1)
	(on ce cd)
	(on cc cb)
	(belong k1 l1)
	(in ce q1)
	(unloaded r1)
	(on cd pallet)
	(in ca p1)
	(in cd q1)
	(equal cc cc)
	(in cb p1)
	(top cf q1)
	(empty k2)
	(adjacent l2 l1)
	(equal ca ca)
	
	;; numbers
	(before zero one)
	(before zero two)
	(before zero three)
	(before zero four)
	(before zero five)
	(before zero six)
	(before zero seven)
	(before zero eight)
	(before zero nine)
	(before zero ten)
	(before zero eleven)
	(before zero twelve)
	(before zero thirteen)
	(before zero fourteen)
	(before zero fifteen)
	(before zero sixteen)
	(before zero seventeen)
	(before one two)
	(before one three)
	(before one four)
	(before one five)
	(before one six)
	(before one seven)
	(before one eight)
	(before one nine)
	(before one ten)
	(before one eleven)
	(before one twelve)
	(before one thirteen)
	(before one fourteen)
	(before one fifteen)
	(before one sixteen)
	(before one seventeen)
	(before two three)
	(before two four)
	(before two five)
	(before two six)
	(before two seven)
	(before two eight)
	(before two nine)
	(before two ten)
	(before two eleven)
	(before two twelve)
	(before two thirteen)
	(before two fourteen)
	(before two fifteen)
	(before two sixteen)
	(before two seventeen)
	(before three four)
	(before three five)
	(before three six)
	(before three seven)
	(before three eight)
	(before three nine)
	(before three ten)
	(before three eleven)
	(before three twelve)
	(before three thirteen)
	(before three fourteen)
	(before three fifteen)
	(before three sixteen)
	(before three seventeen)
	(before four five)
	(before four six)
	(before four seven)
	(before four eight)
	(before four nine)
	(before four ten)
	(before four eleven)
	(before four twelve)
	(before four thirteen)
	(before four fourteen)
	(before four fifteen)
	(before four sixteen)
	(before four seventeen)
	(before five six)
	(before five seven)
	(before five eight)
	(before five nine)
	(before five ten)
	(before five eleven)
	(before five twelve)
	(before five thirteen)
	(before five fourteen)
	(before five fifteen)
	(before five sixteen)
	(before five seventeen)
	(before six seven)
	(before six eight)
	(before six nine)
	(before six ten)
	(before six eleven)
	(before six twelve)
	(before six thirteen)
	(before six fourteen)
	(before six fifteen)
	(before six sixteen)
	(before six seventeen)
	(before seven eight)
	(before seven nine)
	(before seven ten)
	(before seven eleven)
	(before seven twelve)
	(before seven thirteen)
	(before seven fourteen)
	(before seven fifteen)
	(before seven sixteen)
	(before seven seventeen)
	(before eight nine)
	(before eight ten)
	(before eight eleven)
	(before eight twelve)
	(before eight thirteen)
	(before eight fourteen)
	(before eight fifteen)
	(before eight sixteen)
	(before eight seventeen)
	(before nine ten)
	(before nine eleven)
	(before nine twelve)
	(before nine thirteen)
	(before nine fourteen)
	(before nine fifteen)
	(before nine sixteen)
	(before nine seventeen)
	(before ten eleven)
	(before ten twelve)
	(before ten thirteen)
	(before ten fourteen)
	(before ten fifteen)
	(before ten sixteen)
	(before ten seventeen)
	(before eleven twelve)
	(before eleven thirteen)
	(before eleven fourteen)
	(before eleven fifteen)
	(before eleven sixteen)
	(before eleven seventeen)
	(before twelve thirteen)
	(before twelve fourteen)
	(before twelve fifteen)
	(before twelve sixteen)
	(before twelve seventeen)
	(before thirteen fourteen)
	(before thirteen fifteen)
	(before thirteen sixteen)
	(before thirteen seventeen)
	(before fourteen fifteen)
	(before fourteen sixteen)
	(before fourteen seventeen)
	(before fifteen sixteen)
	(before fifteen seventeen)
	(before sixteen seventeen)
	(last zero)
	
	;; found plan
	(plan-action-take one k1 cc cb p1 l1)
	(plan-action-load two k1 r1 cc l1)
	(plan-action-move three r1 l1 l2)
	(plan-action-unload four k2 r1 cc l2)
	(plan-action-put five k2 cc pallet p2 l2)
	(plan-action-take six k1 cb ca p1 l1)
	(plan-action-move seven r1 l2 l1)
	(plan-action-load eight k1 r1 cb l1)
	(plan-action-move nine r1 l1 l2)
	(plan-action-unload ten k2 r1 cb l2)
	(plan-action-put eleven k2 cb pallet q2 l2)
	(plan-action-take twelve k1 ca pallet p1 l1)
	(plan-action-move thirteen r1 l2 l1)
	(plan-action-load fourteen k1 r1 ca l1)
	(plan-action-move fifteen r1 l1 l2)
	(plan-action-unload sixteen k2 r1 ca l2)
	(plan-action-put seventeen k2 ca cc p2 l2)
)
(:goal
	(and
		(in cb q2)
		(in cc p2)
		(in ca p2)
		(not (in pepito))
	)
)
)