(define (problem problem_x)
(:domain airport_fixed_structure)
(:objects
	north south - direction
	light medium heavy - airplanetype
	seg_pp_0_60 seg_ppdoor_0_40 seg_tww1_0_200 seg_twe1_0_200 seg_tww2_0_50 seg_tww3_0_50 seg_tww4_0_50 seg_rww_0_50 seg_rwtw1_0_10 seg_rw_0_400 seg_rwe_0_50 seg_twe4_0_50 seg_rwte1_0_10 seg_twe3_0_50 seg_twe2_0_50 seg_rwte2_0_10 seg_rwtw2_0_10 - segment
	airplane_cfbeg - airplane
	zero one two three four five six seven eight - order)
(:init
	(not_occupied seg_ppdoor_0_40)
	(not_blocked seg_tww2_0_50 airplane_cfbeg)
	(is-moving airplane_cfbeg)
	(not_blocked seg_twe4_0_50 airplane_cfbeg)
	(not_occupied seg_rwte1_0_10)
	(not_blocked seg_ppdoor_0_40 airplane_cfbeg)
	(not_occupied seg_rww_0_50)
	(not_occupied seg_rwe_0_50)
	(not_occupied seg_rwtw1_0_10)
	(blocked seg_rwe_0_50 airplane_cfbeg)
	(not_blocked seg_rwtw1_0_10 airplane_cfbeg)
	(not_occupied seg_rwtw2_0_10)
	(occupied seg_rw_0_400)
	(not_occupied seg_twe1_0_200)
	(not_occupied seg_twe2_0_50)
	(facing airplane_cfbeg south)
	(not_blocked seg_twe3_0_50 airplane_cfbeg)
	(not_occupied seg_rwte2_0_10)
	(not_blocked seg_rwte2_0_10 airplane_cfbeg)
	(not_occupied seg_tww3_0_50)
	(has-type airplane_cfbeg medium)
	(not_blocked seg_tww3_0_50 airplane_cfbeg)
	(not_blocked seg_rwtw2_0_10 airplane_cfbeg)
	(at-segment airplane_cfbeg seg_rw_0_400)
	(not_blocked seg_rww_0_50 airplane_cfbeg)
	(not_occupied seg_twe3_0_50)
	(not_blocked seg_twe1_0_200 airplane_cfbeg)
	(not_blocked seg_rwte1_0_10 airplane_cfbeg)
	(not_occupied seg_pp_0_60)
	(not_blocked seg_tww4_0_50 airplane_cfbeg)
	(not_blocked seg_pp_0_60 airplane_cfbeg)
	(not_occupied seg_tww2_0_50)
	(not_occupied seg_twe4_0_50)
	(not_occupied seg_tww1_0_200)
	(blocked seg_rw_0_400 airplane_cfbeg)
	(not_occupied seg_tww4_0_50)
	(not_blocked seg_twe2_0_50 airplane_cfbeg)
	(not_blocked seg_tww1_0_200 airplane_cfbeg)
	
	;; numbers
	(before zero one)
	(before zero two)
	(before zero three)
	(before zero four)
	(before zero five)
	(before zero six)
	(before zero seven)
	(before zero eight)
	(before one two)
	(before one three)
	(before one four)
	(before one five)
	(before one six)
	(before one seven)
	(before one eight)
	(before two three)
	(before two four)
	(before two five)
	(before two six)
	(before two seven)
	(before two eight)
	(before three four)
	(before three five)
	(before three six)
	(before three seven)
	(before three eight)
	(before four five)
	(before four six)
	(before four seven)
	(before four eight)
	(before five six)
	(before five seven)
	(before five eight)
	(before six seven)
	(before six eight)
	(before seven eight)
	(last zero)
	
	;; found plan
	(plan-action-MOVE_SEG_RW_0_400_SEG_RWW_0_50_SOUTH_SOUTH_MEDIUM one AIRPLANE_CFBEG)
	(plan-action-MOVE_SEG_RWW_0_50_SEG_TWW4_0_50_SOUTH_NORTH_MEDIUM two AIRPLANE_CFBEG)
	(plan-action-MOVE_SEG_TWW4_0_50_SEG_TWW3_0_50_NORTH_NORTH_MEDIUM three AIRPLANE_CFBEG)
	(plan-action-MOVE_SEG_TWW3_0_50_SEG_TWW2_0_50_NORTH_NORTH_MEDIUM four AIRPLANE_CFBEG)
	(plan-action-MOVE_SEG_TWW2_0_50_SEG_TWW1_0_200_NORTH_NORTH_MEDIUM five AIRPLANE_CFBEG)
	(plan-action-MOVE_SEG_TWW1_0_200_SEG_PPDOOR_0_40_NORTH_SOUTH_MEDIUM six AIRPLANE_CFBEG)
	(plan-action-MOVE_SEG_PPDOOR_0_40_SEG_PP_0_60_SOUTH_SOUTH_MEDIUM seven AIRPLANE_CFBEG)
	(plan-action-PARK_SEG_PP_0_60_SOUTH eight AIRPLANE_CFBEG)
)
(:goal
	(and
		(is-parked airplane_cfbeg seg_pp_0_60)
	)
)
)